config/routes.rb
Rails.application.routes.draw do

  get 'maryjka/index'
  get 'about', to: 'maryjka#about', as: :about
  get 'contact', to: 'maryjka#contact', as: :contact

  resources :albums
  resources :subscribers

  root 'maryjka#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }

  def self.newest(n)
    order(id: :desc).limit(n)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :name, :email, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.order(start_date: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_instagram
  before_action :set_subscriber

  def set_instagram
    @instagram = Instagram.user_recent_media("2536068603", { :count => 6 })
  end

  def set_subscriber
    @subscriber = Subscriber.new
  end
  
end

app/controllers/maryjka_controller.rb
class MaryjkaController < ApplicationController
  def index
    @newest_albums = Album.newest(4)
  end

  def about
  end

  def contact
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscriber = Subscriber.new
  end

  def create
    @subscriber= Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Saved successfully.' }
        format.js
        format.json { render json: @subscriber, status: :created, location: @subscriber }
        cookies[:saved_subscriber] = true
      else
        format.html { render action: 'new' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def subscriber_params
    params.require(:subscriber).permit(:name, :email)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

  def copyright_notice_year_range(start_year)
    start_year = start_year.to_i
    current_year = Time.new.year

    current_year > start_year ? "#{start_year} - #{current_year}" : "#{start_year}"
  end
end

app/helpers/maryjka_helper.rb
module MaryjkaHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/albums/index.html.erb
<!-- Page Title -->
<div class="page-title-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 wow fadeIn">
	<i class="fa fa-camera"></i>
	<h1>Albumy z podróży /</h1>
      </div>
    </div>
  </div>
</div>

<!-- Albumy -->
<div class="portfolio-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 portfolio-filters wow fadeInLeft">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 portfolio-masonry">
	<% @albums.each do |album| %>
	<div class="portfolio-box">
	  <div class="portfolio-box-container">
	    <%= link_to image_tag(album.logo_url, alt: album.title), album.album_url %>
	    <div class="portfolio-box-text">
	      <h3><%= album.title %></h3>
	      <p><%= album.text %></p>
	    </div>
	  </div>
	</div>
	<% end %>
      </div>
    </div>
  </div>	
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-3 footer-box wow fadeInUp">
	<h4>O mnie</h4>
	<div class="footer-box-text">
	  <p>
	    W budowie.
	  </p>
	  <p><%= link_to "Więcej", about_path %></p>
	</div>
      </div>
      <div class="col-sm-3 footer-box wow fadeInDown">
	<%= render 'subscribers/index'  %>
      </div>
      <div class="col-sm-3 footer-box wow fadeInUp">
	<h4>Instagram</h4>
	<div class="footer-box-text instagram-feed">
	  <% @instagram.each do |instagram| %>
	  <%= link_to image_tag(instagram.images.low_resolution.url), instagram.link  %>
	  <% end %>
	</div>
      </div>
      <div class="col-sm-3 footer-box wow fadeInDown">
	<h4>Kontakt</h4>
	<div class="footer-box-text footer-box-text-contact">
	  <p><i class="fa fa-map-marker"></i> Adres</p>
	  <p><i class="fa fa-phone"></i> Telefon</p>
	  <p><i class="fa fa-user"></i> Skype</p>
	  <p><i class="fa fa-envelope"></i> Email</p>
	</div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 wow fadeIn">
	<div class="footer-border"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7 footer-copyright wow fadeIn">
	&copy; <%= copyright_notice_year_range(2017) %> <%= link_to "Maryjka.pl", "#" %>  Wszelkie prawa zatrzeżone.<br/>
	Szablon dzięki <a href="http://azmind.com/free-bootstrap-themes-templates/">Azmind</a>.
      </div>
      <div class="col-sm-5 footer-social wow fadeIn">
	<a href="#"><i class="fa fa-facebook"></i></a>
	<a href="#"><i class="fa fa-dribbble"></i></a>
	<a href="#"><i class="fa fa-twitter"></i></a>
	<a href="#"><i class="fa fa-pinterest"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Top menu -->
<nav class="navbar" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
         <span class="sr-only">Toggle navigation</span>
	 <span class="icon-bar"></span>
	 <span class="icon-bar"></span>
	 <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="index.html">Maryjka.pl</a>
     </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="top-navbar-1">
       <ul class="nav navbar-nav navbar-right">
	 <li class="<%= active_class(root_path) %>"><%= link_to root_path do %>
	   <i class="fa fa-home"></i><br>START
	   <% end %>
	 </li>
	 <li class="<%= active_class(albums_path) %>"><%= link_to albums_path do %>
	   <i class="fa fa-camera"></i><br>ALBUMY
	   <% end %>
	 </li>
	 <li class="<%= active_class(about_path) %>"><%= link_to about_path do %>
	   <i class="fa fa-user"></i><br>O MNIE
	   <% end %>
	 </li>
	 <li class="<%=active_class(contact_path) %>"><%= link_to contact_path do %>
	   <i class="fa fa-envelope"></i><br>KONTAKT
	   <% end %>
	 </li>
       </ul>
     </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Maryjka</title>
    
    <%= csrf_meta_tags %>

    <!-- Favicon and touch icons -->
    <%= favicon_link_tag %>
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <!-- CSS -->
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400italic,400','application.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Droid+Sans','application.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lobster','application.css' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/maryjka/_newest.html.erb
<!-- Latest work -->
<div class="work-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 work-title wow fadeIn">
	<h2>Najnowsze albumy</h2>
      </div>
    </div>
    
    <div class="row">
      <% @newest_albums.each do |album| %>
      <div class="col-sm-3">
	<div class="work wow fadeInUp">
	  <%= link_to image_tag_with_at2x(album.logo_url, alt: album.title), album.album_url %>
	  <h3><%= album.title %></h3>
	  <div class="work-bottom">
	    <%= link_to album.album_url, { :class => "big-link-2" } do %>
	    <i class="fa fa-search"></i>
	    <% end %>
	    <%= link_to albums_path, { :class => "big-link-2" } do %>
	    <i class="fa fa-link"></i>
	    <% end %>
	  </div>
	</div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/maryjka/_services.html.erb
<!-- Services -->
<div class="services-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 services-title wow fadeIn">
	<h2>Znajdziesz tu</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
	<div class="service wow fadeInUp">
	  <div class="service-icon"><i class="fa fa-camera"></i></div>
	  <h3>Albumy</h3>
	  <p>Zdjęcia z naszych podróży w bliskie i dalekie strony oraz z wypadów w góry.</p>
	  <%= link_to "Więcej", albums_path, { :class => "big-link-1" } %>
	</div>
      </div>
      <div class="col-sm-3">
	<div class="service wow fadeInDown">
	  <div class="service-icon"><i class="fa fa-book"></i></div>
	  <h3>Blog</h3>
	  <p>Obserwacje, opowieści i relacje z naszych podróży - w przygotowaniu.</p>
	  <%= link_to "Więcej", "http://www.marianka.geoblog.pl", { :class => "big-link-1" } %>
	</div>
      </div>
      <div class="col-sm-3">
	<div class="service wow fadeInUp">
	  <div class="service-icon"><i class="fa fa-magic"></i></div>
	  <h3>Jeszcze cos 1</h3>
	  <p>Pewnie jeszcze coś tu powstanie najbardziej ciekawego na świecie.</p>
	  <%= link_to "Więcej", albums_path, { :class => "big-link-1" } %>
	</div>
      </div>
      <div class="col-sm-3">
	<div class="service wow fadeInDown">
	  <div class="service-icon"><i class="fa fa-print"></i></div>
	  <h3>Jeszcze cos 2</h3>
	  <p>Tutaj pewnie też jeszcze coś powstanie super inspirującego i interesującego.</p>
	  <%= link_to "Więcej", albums_path, { :class => "big-link-1" } %>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/maryjka/_slider.html.erb
<!-- Slider 2 -->
<div class="slider-2-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 slider-2-text wow fadeInUp">
        <h1>Serdecznie zapraszam na <span class="violet">Maryjka</span>.pl</h1>
	<p>Znajdziesz tu opowieści z podróży, subiektywne obserwacje, zdjęcia i inspiracje.</p>
      </div>
    </div>
  </div>
</div>

app/views/maryjka/_wip.html.erb
<div class="tmp-container">
  <h3>Strona w budowie</h3>
</div>

app/views/maryjka/about.html.erb
<%= render 'wip'%>

app/views/maryjka/contact.html.erb
<%= render 'wip'%>

app/views/maryjka/index.html.erb
<%= render 'maryjka/slider' %>
<% render 'maryjka/services' %>
<%= render 'maryjka/newest' %>

        <!-- Javascript -->
<!--        <script src="assets/js/bootstrap-hover-dropdown.min.js"></script> -->
<!--        <script src="assets/js/jquery.backstretch.min.js"></script> -->
<!--        <script src="assets/js/masonry.pkgd.min.js"></script> -->

app/views/subscribers/_index.html.erb
<h4>Subskrypcja</h4>
<div class="footer-box-text footer-box-text-subscribe">
  <% if cookies[:saved_subscriber] %>
    Dzięki za zapisanie się!
  <% else %>
    <p>Zostaw swój email, aby nie przegapić żadnych nowości.</p>
    <%= form_for @subscriber do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Imię" %>
        <%= f.email_field :email, placeholder: "Email" %>
      </div>
      <%= f.button "Subskrybuj", class: "btn" %>
    <% end %>
    <p class="success-message"></p>
    <p class="error-message"></p>
  <% end %>
</div>